apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: "2020-01-28T01:59:30Z"
  labels:
    run: hello
  name: hello
  namespace: mynamespace
  resourceVersion: "1085671"
  selfLink: /apis/batch/v1beta1/namespaces/mynamespace/cronjobs/hello
  uid: 9ebb6e42-f9c1-4301-a002-d0ceede4903b
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      completions: 17
      template:
        metadata:
          creationTimestamp: null
          labels:
            run: hello
        spec:
          containers:
          - args:
            - sh
            - -c
            - who
            image: busybox
            imagePullPolicy: Always
            name: hello
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: '*/1 * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: "2020-01-28T02:00:00Z"
