apiVersion: v1
kind: Pod
metadata:
   name: configmap-demo-pod2
spec:
 containers:
 - name: test-container
   image: busybox
   command: [ "/bin/sh", "-c", "expr $a + $b"]
   envFrom:
      - configMapRef:
          name: mathconfig 
          key: a
   envFrom:
      - configMapRef:
          name: mathconfig 
          key: b
 restartPolicy: Never 
          
