apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-configuration
  name: kplabs-configuration
spec:
  replicas: 3
  selector:
    matchLabels:
      run: kplabs-configuration
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kplabs-configuration
    spec:
      containers:
      - image: nginx
        name: kplabs-configuration
        resources: {}
status: {}
