apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-container
  name: first-container
spec:
  containers:
  - image: nginx
    name: first-container
  - image: mykplabs/kubernetes:nginx
    name: second-container
  - image: busybox
    name: third-container
    command:
     - sleep
     - "3600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
