apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-policy
  namespace: dgkanatsios
spec:
  podSelector:
    matchLabels:
      run: nginx 
  policyTypes:
  - Ingress
  ingress:
  - from:
     - podSelector:
        matchLabels:
           access: 'true'
