apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kplabs-logging
  name: kplabs-logging
spec:
  containers:
  - args:
    - sh
    - -c
    - '      i=0;'
    image: nginx
    name: kplabs-logging
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
