apiVersion: apps/v1
kind: Deployment
metadata:
    name: mydeployment
    labels:
       app: myapp
       type: front-end
spec:
  template:
    metadata:
      name: myapp-pod
      labels:
         app: myapp
         type: front-end
    spec:
       containers:
          - name: ngnix
            image: ngnix
  replicas: 3
  selector:
      matchLabels:
          type: front-end 
 
