apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx1
  name: nginx1
spec:
  containers:
  - image: nginx
    name: nginx1
    resources: {}
    env:
      - name: DB_USER 
        valueFrom:
          secretKeyRef:
            name: kplabs-secret
            key: user
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: kplabs-secret
            key: pass
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
