apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    creationTimestamp: 2019-12-11T06:38:26Z
    name: ubuntu-sleeper
    namespace: default
    resourceVersion: "1452"
    selfLink: /api/v1/namespaces/default/pods/ubuntu-sleeper
    uid: d611cf5e-1be0-11ea-9ee9-0242ac11003e
  spec:
    containers:
    - command:
      - sleep
      - "4800"
      image: ubuntu
      imagePullPolicy: Always
      name: ubuntu
      securityContext:
        capabilities:
           add: ["SYS_TIME"]

      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-5q6vs
        readOnly: true
    dnsPolicy: ClusterFirst
    nodeName: node01
    priority: 0
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
    volumes:
    - name: default-token-5q6vs
      secret:
        defaultMode: 420
        secretName: default-token-5q6vs
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2019-12-11T06:38:26Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2019-12-11T06:38:32Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: null
      status: "True"
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: 2019-12-11T06:38:26Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://92764cd72e29ac07bee25c2a230e0b744835be6cfd6e673d48b674851e4d1658
      image: ubuntu:latest
      imageID: docker-pullable://ubuntu@sha256:6e9f67fa63b0323e9a1e587fd71c561ba48a034504fb804fd26fd8800039835d
      lastState: {}
      name: ubuntu
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2019-12-11T06:38:32Z
    hostIP: 172.17.0.65
    phase: Running
    podIP: 10.32.0.2
    qosClass: BestEffort
    startTime: 2019-12-11T06:38:26Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
